default: &default
  adapter: mysql2
  encoding: utf8
  username: HJU9iUdv9F
  password: ML9xtA4qvM
  host: remotemysql.com
  port: 3306

development:
  <<: *default
  database: HJU9iUdv9F

test:
  <<: *default
  database: HJU9iUdv9F

production:
  <<: *default
  database: HJU9iUdv9F